use std::path::Path;

use moraine_model::definition::{GameDef, LoaderObject, RuntimeDef};
use moraine_model::genesis::GenesisKind;
use moraine_model::signed::SignedObject;
use serde::{Deserialize, Serialize};

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct DefinitionLock {
	#[serde(default)]
	pub definition: Vec<LockedDefinition>,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct LockedDefinition {
	pub kind: String,
	pub id: String,
	#[serde(default, skip_serializing_if = "Option::is_none")]
	pub home: Option<String>,
}

fn collection(kind: GenesisKind) -> &'static str {
	match kind {
		GenesisKind::Game => "game",
		GenesisKind::Loader => "loader",
		GenesisKind::Runtime => "runtime",
		GenesisKind::Project => "project",
	}
}

fn identity(bytes: &[u8]) -> Option<(GenesisKind, String)> {
	if let Ok(signed) = SignedObject::<GameDef>::from_bytes(bytes) {
		return Some((GenesisKind::Game, signed.payload.game_id));
	}
	if let Ok(signed) = SignedObject::<LoaderObject>::from_bytes(bytes) {
		return match signed.payload {
			LoaderObject::Definition(definition) => Some((GenesisKind::Loader, definition.loader_id)),
			LoaderObject::Release(_) | LoaderObject::Acceptance(_) => None,
		};
	}
	if let Ok(signed) = SignedObject::<RuntimeDef>::from_bytes(bytes) {
		return Some((GenesisKind::Runtime, signed.payload.runtime_id));
	}
	None
}

pub fn write_lock(directory: &Path, home: Option<&str>, out: &Path) -> Result<usize, String> {
	let mut paths = std::fs::read_dir(directory)
		.map_err(|error| format!("{}: {error}", directory.display()))?
		.filter_map(|entry| entry.ok().map(|entry| entry.path()))
		.filter(|path| path.is_file())
		.collect::<Vec<_>>();
	paths.sort();

	let mut entries: Vec<(GenesisKind, String)> = Vec::new();
	for path in paths {
		let bytes = std::fs::read(&path).map_err(|error| format!("{}: {error}", path.display()))?;
		if let Some(identity) = identity(&bytes) {
			entries.push(identity);
		}
	}
	entries.sort_by_key(|(kind, id)| {
		let order = match kind {
			GenesisKind::Game => 0,
			GenesisKind::Runtime => 1,
			GenesisKind::Loader => 2,
			GenesisKind::Project => 3,
		};
		(order, id.clone())
	});
	if entries.is_empty() {
		return Err(format!("{} holds no definition objects", directory.display()));
	}

	let home = home.map(|home| home.trim_end_matches('/').to_string());
	let lock = DefinitionLock {
		definition: entries
			.iter()
			.map(|(kind, id)| LockedDefinition {
				kind: collection(*kind).to_string(),
				id: id.clone(),
				home: home.clone(),
			})
			.collect(),
	};
	let text = toml::to_string_pretty(&lock).map_err(|error| error.to_string())?;
	let header = "# Generated by `moraine-publish lock-definitions` from the signed definition\n# set. Apply it to an instance with `moraine-publish sync-definitions --lock`.\n";
	std::fs::write(out, format!("{header}{text}")).map_err(|error| format!("{}: {error}", out.display()))?;
	println!("wrote {} definition(s) to {}", lock.definition.len(), out.display());
	Ok(lock.definition.len())
}

#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	fn rejects_unknown_lock_fields() {
		let top_level = r#"
unexpected = true
[[definition]]
kind = "game"
id = "gd:sha256:aa"
"#;
		let entry = r#"
[[definition]]
kind = "game"
id = "gd:sha256:aa"
unexpected = true
"#;
		assert!(toml::from_str::<DefinitionLock>(top_level).is_err());
		assert!(toml::from_str::<DefinitionLock>(entry).is_err());
	}
}
